spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: user-server
server:
  port: 8877


eureka:
  client:
    service-url:
      defaultZone: http://1:1@localhost:8861/eureka/


